import type { BulkCreateMatchItem } from "@/src/lib/tournament-types";

type OfficialMatch = BulkCreateMatchItem;

const GROUP_MATCHES: OfficialMatch[] = [
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "09:30 hs",
    category: "Categoría 1 Federado",
    court: "Cancha 1 (Sintético)",
    teamA: "Los Candiles (1F)",
    teamB: "LOS CERROS (1F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "09:55 hs",
    category: "Categoría 1 Federado",
    court: "Cancha 1 (Sintético)",
    teamA: "BUEN AYRE (1F)",
    teamB: "PORTEZUELO (1F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "10:20 hs",
    category: "Categoría 1 Federado",
    court: "Cancha 1 (Sintético)",
    teamA: "TORREÓN (1F)",
    teamB: "CRISOL (1F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "10:45 hs",
    category: "Categoría 1 Federado",
    court: "Cancha 1 (Sintético)",
    teamA: "Los Candiles (1F)",
    teamB: "BUEN AYRE (1F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "11:10 hs",
    category: "Categoría 1 Federado",
    court: "Cancha 1 (Sintético)",
    teamA: "LOS CERROS (1F)",
    teamB: "TORREÓN (1F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "11:35 hs",
    category: "Categoría 1 Federado",
    court: "Cancha 1 (Sintético)",
    teamA: "CRISOL (1F)",
    teamB: "PORTEZUELO (1F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "12:00 hs",
    category: "Categoría 1 Federado",
    court: "Cancha 1 (Sintético)",
    teamA: "Los Candiles (1F)",
    teamB: "TORREÓN (1F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "12:25 hs",
    category: "Categoría 1 Federado",
    court: "Cancha 1 (Sintético)",
    teamA: "LOS CERROS (1F)",
    teamB: "BUEN AYRE (1F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "14:10 hs",
    category: "Categoría 1 Federado",
    court: "Cancha 1 (Sintético)",
    teamA: "TORREÓN (1F)",
    teamB: "PORTEZUELO (1F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "14:35 hs",
    category: "Categoría 1 Federado",
    court: "Cancha 1 (Sintético)",
    teamA: "BUEN AYRE (1F)",
    teamB: "CRISOL (1F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "15:25 hs",
    category: "Categoría 1 Federado",
    court: "Cancha 1 (Sintético)",
    teamA: "Los Candiles (1F)",
    teamB: "PORTEZUELO (1F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "15:50 hs",
    category: "Categoría 1 Federado",
    court: "Cancha 1 (Sintético)",
    teamA: "LOS CERROS (1F)",
    teamB: "CRISOL (1F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "09:30 hs",
    category: "Categoría 2 Federado",
    court: "Cancha 2 (Sintético)",
    teamA: "TORREÓN (2F)",
    teamB: "PORTEZUELO (2F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "09:55 hs",
    category: "Categoría 2 Federado",
    court: "Cancha 2 (Sintético)",
    teamA: "MIRASOLES (2F)",
    teamB: "Los Candiles (2F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "10:20 hs",
    category: "Categoría 2 Federado",
    court: "Cancha 2 (Sintético)",
    teamA: "BUEN AYRE (2F)",
    teamB: "PORTEZUELO (2F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "10:45 hs",
    category: "Categoría 2 Federado",
    court: "Cancha 2 (Sintético)",
    teamA: "LOS CERROS (2F)",
    teamB: "TORREÓN (2F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "11:10 hs",
    category: "Categoría 2 Federado",
    court: "Cancha 2 (Sintético)",
    teamA: "Los Candiles (2F)",
    teamB: "BUEN AYRE (2F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "11:35 hs",
    category: "Categoría 2 Federado",
    court: "Cancha 2 (Sintético)",
    teamA: "MIRASOLES (2F)",
    teamB: "PORTEZUELO (2F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "12:00 hs",
    category: "Categoría 2 Federado",
    court: "Cancha 2 (Sintético)",
    teamA: "LOS CERROS (2F)",
    teamB: "Los Candiles (2F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "12:25 hs",
    category: "Categoría 2 Federado",
    court: "Cancha 2 (Sintético)",
    teamA: "BUEN AYRE (2F)",
    teamB: "TORREÓN (2F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "14:10 hs",
    category: "Categoría 2 Federado",
    court: "Cancha 2 (Sintético)",
    teamA: "TORREÓN (2F)",
    teamB: "MIRASOLES (2F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "15:00 hs",
    category: "Categoría 2 Federado",
    court: "Cancha 2 (Sintético)",
    teamA: "LOS CERROS (2F)",
    teamB: "PORTEZUELO (2F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "15:50 hs",
    category: "Categoría 2 Federado",
    court: "Cancha 2 (Sintético)",
    teamA: "BUEN AYRE (2F)",
    teamB: "MIRASOLES (2F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "09:30 hs",
    category: "Categoría 3 Federado",
    court: "Cancha 3 (Sintético)",
    teamA: "BUEN AYRE (3F)",
    teamB: "MIRASOLES (3F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "09:55 hs",
    category: "Categoría 3 Federado",
    court: "Cancha 3 (Sintético)",
    teamA: "Los Candiles (3F)",
    teamB: "PORTEZUELO (3F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "10:20 hs",
    category: "Categoría 3 Federado",
    court: "Cancha 3 (Sintético)",
    teamA: "TORREÓN (3F)",
    teamB: "CRISOL (3F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "10:45 hs",
    category: "Categoría 3 Federado",
    court: "Cancha 3 (Sintético)",
    teamA: "BUEN AYRE (3F)",
    teamB: "Los Candiles (3F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "11:10 hs",
    category: "Categoría 3 Federado",
    court: "Cancha 3 (Sintético)",
    teamA: "PORTEZUELO (3F)",
    teamB: "MIRASOLES (3F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "11:35 hs",
    category: "Categoría 3 Federado",
    court: "Cancha 3 (Sintético)",
    teamA: "TORREÓN (3F)",
    teamB: "Los Candiles (3F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "12:00 hs",
    category: "Categoría 3 Federado",
    court: "Cancha 3 (Sintético)",
    teamA: "CRISOL (3F)",
    teamB: "BUEN AYRE (3F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "12:25 hs",
    category: "Categoría 3 Federado",
    court: "Cancha 3 (Sintético)",
    teamA: "TORREÓN (3F)",
    teamB: "PORTEZUELO (3F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "14:35 hs",
    category: "Categoría 3 Federado",
    court: "Cancha 3 (Sintético)",
    teamA: "MIRASOLES (3F)",
    teamB: "CRISOL (3F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "15:25 hs",
    category: "Categoría 3 Federado",
    court: "Cancha 3 (Sintético)",
    teamA: "PORTEZUELO (3F)",
    teamB: "BUEN AYRE (3F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "15:50 hs",
    category: "Categoría 3 Federado",
    court: "Cancha 3 (Sintético)",
    teamA: "Los Candiles (3F)",
    teamB: "CRISOL (3F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "09:30 hs",
    category: "Categoría 1 Colegial",
    court: "Cancha 4 (Pasto)",
    teamA: "PORTEZUELO (1C)",
    teamB: "CRISOL (1C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "09:55 hs",
    category: "Categoría 1 Colegial",
    court: "Cancha 4 (Pasto)",
    teamA: "LOS CERROS (1C)",
    teamB: "BUEN AYRE (1C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "10:20 hs",
    category: "Categoría 1 Colegial",
    court: "Cancha 4 (Pasto)",
    teamA: "TORREÓN (1C)",
    teamB: "Los Candiles (1C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "10:45 hs",
    category: "Categoría 1 Colegial",
    court: "Cancha 4 (Pasto)",
    teamA: "PORTEZUELO (1C)",
    teamB: "LOS CERROS (1C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "11:10 hs",
    category: "Categoría 1 Colegial",
    court: "Cancha 4 (Pasto)",
    teamA: "Los Candiles (1C)",
    teamB: "CRISOL (1C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "11:35 hs",
    category: "Categoría 1 Colegial",
    court: "Cancha 4 (Pasto)",
    teamA: "BUEN AYRE (1C)",
    teamB: "TORREÓN (1C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "12:00 hs",
    category: "Categoría 1 Colegial",
    court: "Cancha 4 (Pasto)",
    teamA: "CRISOL (1C)",
    teamB: "LOS CERROS (1C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "12:25 hs",
    category: "Categoría 1 Colegial",
    court: "Cancha 4 (Pasto)",
    teamA: "Los Candiles (1C)",
    teamB: "PORTEZUELO (1C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "14:10 hs",
    category: "Categoría 1 Colegial",
    court: "Cancha 4 (Pasto)",
    teamA: "Los Candiles (1C)",
    teamB: "BUEN AYRE (1C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "15:00 hs",
    category: "Categoría 1 Colegial",
    court: "Cancha 4 (Pasto)",
    teamA: "LOS CERROS (1C)",
    teamB: "TORREÓN (1C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "15:50 hs",
    category: "Categoría 1 Colegial",
    court: "Cancha 4 (Pasto)",
    teamA: "PORTEZUELO (1C)",
    teamB: "BUEN AYRE (1C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "09:30 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "BUEN AYRE (2C)",
    teamB: "CRISOL (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "09:55 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "LOS CERROS (2C)",
    teamB: "TORREÓN (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "10:20 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "CRISOL (2C)",
    teamB: "PORTEZUELO (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "10:45 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "LOS CERROS (2C)",
    teamB: "BUEN AYRE (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "11:10 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "PORTEZUELO (2C)",
    teamB: "MIRASOLES (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "11:35 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "BUEN AYRE (2C)",
    teamB: "TORREÓN (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "12:00 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "LOS CERROS (2C)",
    teamB: "PORTEZUELO (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "12:25 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "MIRASOLES (2C)",
    teamB: "BUEN AYRE (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "14:10 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "TORREÓN (2C)",
    teamB: "PORTEZUELO (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "14:35 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "Los Candiles (2C)",
    teamB: "LOS CERROS (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "15:00 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "BUEN AYRE (2C)",
    teamB: "PORTEZUELO (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "15:25 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "CRISOL (2C)",
    teamB: "TORREÓN (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "15:50 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "MIRASOLES (2C)",
    teamB: "LOS CERROS (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "09:30 hs",
    category: "Categoría 3 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "Los Candiles (3C)",
    teamB: "PORTEZUELO (3C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "09:55 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "MIRASOLES (2C)",
    teamB: "Los Candiles (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "10:20 hs",
    category: "Categoría 3 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "BUEN AYRE (3C)",
    teamB: "MIRASOLES (3C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "10:45 hs",
    category: "Categoría 3 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "TORREÓN (3C)",
    teamB: "CRISOL (3C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "11:10 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "CRISOL (2C)",
    teamB: "Los Candiles (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "11:35 hs",
    category: "Categoría 3 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "BUEN AYRE (3C)",
    teamB: "Los Candiles (3C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "12:00 hs",
    category: "Categoría 3 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "MIRASOLES (3C)",
    teamB: "PORTEZUELO (3C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "12:25 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "Los Candiles (2C)",
    teamB: "TORREÓN (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "14:10 hs",
    category: "Categoría 3 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "PORTEZUELO (3C)",
    teamB: "BUEN AYRE (3C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "14:35 hs",
    category: "Categoría 3 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "TORREÓN (3C)",
    teamB: "Los Candiles (3C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "15:00 hs",
    category: "Categoría 3 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "BUEN AYRE (3C)",
    teamB: "CRISOL (3C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "15:25 hs",
    category: "Categoría 3 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "MIRASOLES (3C)",
    teamB: "TORREÓN (3C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia1",
    date: "Día 1",
    timeLabel: "15:50 hs",
    category: "Categoría 3 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "PORTEZUELO (3C)",
    teamB: "CRISOL (3C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "09:55 hs",
    category: "Categoría 1 Federado",
    court: "Cancha 1 (Sintético)",
    teamA: "TORREÓN (1F)",
    teamB: "BUEN AYRE (1F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "09:30 hs",
    category: "Categoría 1 Federado",
    court: "Cancha 1 (Sintético)",
    teamA: "Los Candiles (1F)",
    teamB: "CRISOL (1F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "11:10 hs",
    category: "Categoría 1 Federado",
    court: "Cancha 1 (Sintético)",
    teamA: "LOS CERROS (1F)",
    teamB: "PORTEZUELO (1F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "09:30 hs",
    category: "Categoría 2 Federado",
    court: "Cancha 2 (Sintético)",
    teamA: "Los Candiles (2F)",
    teamB: "TORREÓN (2F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "09:55 hs",
    category: "Categoría 2 Federado",
    court: "Cancha 2 (Sintético)",
    teamA: "BUEN AYRE (2F)",
    teamB: "LOS CERROS (2F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "10:20 hs",
    category: "Categoría 2 Federado",
    court: "Cancha 2 (Sintético)",
    teamA: "PORTEZUELO (2F)",
    teamB: "Los Candiles (2F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "11:10 hs",
    category: "Categoría 2 Federado",
    court: "Cancha 2 (Sintético)",
    teamA: "MIRASOLES (2F)",
    teamB: "LOS CERROS (2F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "09:30 hs",
    category: "Categoría 3 Federado",
    court: "Cancha 3 (Sintético)",
    teamA: "MIRASOLES (3F)",
    teamB: "TORREÓN (3F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "09:55 hs",
    category: "Categoría 3 Federado",
    court: "Cancha 3 (Sintético)",
    teamA: "PORTEZUELO (3F)",
    teamB: "CRISOL (3F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "10:20 hs",
    category: "Categoría 3 Federado",
    court: "Cancha 3 (Sintético)",
    teamA: "BUEN AYRE (3F)",
    teamB: "TORREÓN (3F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "10:45 hs",
    category: "Categoría 3 Federado",
    court: "Cancha 3 (Sintético)",
    teamA: "Los Candiles (3F)",
    teamB: "MIRASOLES (3F)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "09:30 hs",
    category: "Categoría 1 Colegial",
    court: "Cancha 4 (Pasto)",
    teamA: "CRISOL (1C)",
    teamB: "TORREÓN (1C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "09:55 hs",
    category: "Categoría 1 Colegial",
    court: "Cancha 4 (Pasto)",
    teamA: "LOS CERROS (1C)",
    teamB: "Los Candiles (1C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "10:45 hs",
    category: "Categoría 1 Colegial",
    court: "Cancha 4 (Pasto)",
    teamA: "CRISOL (1C)",
    teamB: "BUEN AYRE (1C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "11:10 hs",
    category: "Categoría 1 Colegial",
    court: "Cancha 4 (Pasto)",
    teamA: "PORTEZUELO (1C)",
    teamB: "TORREÓN (1C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "09:30 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "Los Candiles (2C)",
    teamB: "BUEN AYRE (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "09:55 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "LOS CERROS (2C)",
    teamB: "CRISOL (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "10:20 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "MIRASOLES (2C)",
    teamB: "TORREÓN (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "10:45 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "PORTEZUELO (2C)",
    teamB: "Los Candiles (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "11:10 hs",
    category: "Categoría 2 Colegial",
    court: "Cancha 5 (Pasto)",
    teamA: "MIRASOLES (2C)",
    teamB: "CRISOL (2C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "09:30 hs",
    category: "Categoría 3 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "Los Candiles (3C)",
    teamB: "MIRASOLES (3C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "09:55 hs",
    category: "Categoría 3 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "TORREÓN (3C)",
    teamB: "BUEN AYRE (3C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "10:20 hs",
    category: "Categoría 3 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "Los Candiles (3C)",
    teamB: "CRISOL (3C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "10:45 hs",
    category: "Categoría 3 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "TORREÓN (3C)",
    teamB: "PORTEZUELO (3C)",
    stage: "grupo",
    featured: false,
  },
  {
    day: "dia2",
    date: "Día 2",
    timeLabel: "11:10 hs",
    category: "Categoría 3 Colegial",
    court: "Cancha 6 (Pasto)",
    teamA: "CRISOL (3C)",
    teamB: "MIRASOLES (3C)",
    stage: "grupo",
    featured: false,
  },
];

const CATEGORY_DEFINITIONS = [
  { code: "1F", category: "Categoría 1 Federado", court: "Cancha 1 (Sintético)" },
  { code: "2F", category: "Categoría 2 Federado", court: "Cancha 2 (Sintético)" },
  { code: "3F", category: "Categoría 3 Federado", court: "Cancha 3 (Sintético)" },
  { code: "1C", category: "Categoría 1 Colegial", court: "Cancha 4 (Pasto)" },
  { code: "2C", category: "Categoría 2 Colegial", court: "Cancha 5 (Pasto)" },
  { code: "3C", category: "Categoría 3 Colegial", court: "Cancha 6 (Pasto)" },
] as const;

const DEFINITION_MATCHES: OfficialMatch[] = CATEGORY_DEFINITIONS.flatMap(({ category, court }) => [
  {
    day: "dia2", date: "Día 2", timeLabel: "11:45 hs", category, court,
    teamA: "5-6 · 5°", teamB: "5-6 · 6°", stage: "final", featured: false,
  },
  {
    day: "dia2", date: "Día 2", timeLabel: "12:15 hs", category, court,
    teamA: "1-4 · 1°", teamB: "1-4 · 4°", stage: "semifinal", featured: true,
  },
  {
    day: "dia2", date: "Día 2", timeLabel: "12:45 hs", category, court,
    teamA: "2-3 · 2°", teamB: "2-3 · 3°", stage: "semifinal", featured: true,
  },
  {
    day: "dia2", date: "Día 2", timeLabel: "14:15 hs", category, court,
    teamA: "3-4 · SF A", teamB: "3-4 · SF B", stage: "final", featured: false,
  },
  {
    day: "dia2", date: "Día 2", timeLabel: "14:45 hs", category, court,
    teamA: "1-2 · SF A", teamB: "1-2 · SF B", stage: "final", featured: true,
  },
]);

export const OFFICIAL_FIXTURE_2026: OfficialMatch[] = [...GROUP_MATCHES, ...DEFINITION_MATCHES];

export const OFFICIAL_MOVED_MATCHES = GROUP_MATCHES.filter(
  (match) =>
    match.day === "dia1" &&
    match.category === "Categoría 2 Colegial" &&
    match.court === "Cancha 6 (Pasto)",
);

export const OFFICIAL_FIXTURE_SUMMARY = {
  total: OFFICIAL_FIXTURE_2026.length,
  group: GROUP_MATCHES.length,
  definition: DEFINITION_MATCHES.length,
  moved: OFFICIAL_MOVED_MATCHES.length,
};

export function validateOfficialFixture() {
  const errors: string[] = [];
  const expectedGroupCounts: Record<string, number> = {
    "Categoría 1 Federado": 15,
    "Categoría 2 Federado": 15,
    "Categoría 3 Federado": 15,
    "Categoría 1 Colegial": 15,
    "Categoría 2 Colegial": 21,
    "Categoría 3 Colegial": 15,
  };

  if (OFFICIAL_FIXTURE_2026.length !== 126) errors.push("El fixture debe tener 126 partidos.");
  if (GROUP_MATCHES.length !== 96) errors.push("La fase de grupos debe tener 96 partidos.");
  if (DEFINITION_MATCHES.length !== 30) errors.push("La definición debe tener 30 partidos.");
  if (OFFICIAL_MOVED_MATCHES.length !== 3) errors.push("Deben existir exactamente 3 partidos reubicados de 2C en Cancha 6.");

  for (const [category, expectedCount] of Object.entries(expectedGroupCounts)) {
    const matches = GROUP_MATCHES.filter((match) => match.category === category);
    if (matches.length !== expectedCount) {
      errors.push(`${category}: se esperaban ${expectedCount} partidos y hay ${matches.length}.`);
      continue;
    }

    const pairKeys = new Set<string>();
    const teams = new Set<string>();
    const occupied = new Set<string>();

    for (const match of matches) {
      const a = baseTeam(match.teamA);
      const b = baseTeam(match.teamB);
      teams.add(a);
      teams.add(b);
      const pair = [a, b].sort().join("::");
      if (pairKeys.has(pair)) errors.push(`${category}: cruce duplicado ${a} vs ${b}.`);
      pairKeys.add(pair);

      for (const team of [a, b]) {
        const slot = `${match.day}::${match.timeLabel}::${team}`;
        if (occupied.has(slot)) errors.push(`${category}: ${team} tiene dos partidos en ${match.timeLabel}.`);
        occupied.add(slot);
      }
    }

    const expectedPairs = (teams.size * (teams.size - 1)) / 2;
    if (pairKeys.size !== expectedPairs) {
      errors.push(`${category}: faltan o sobran cruces (${pairKeys.size}/${expectedPairs}).`);
    }
  }

  return { ok: errors.length === 0, errors };
}

function baseTeam(value: string) {
  return value.replace(/\s*\([^)]*\)\s*$/, "").trim();
}
