-- Copa APDES: ejecutar una sola vez en el SQL Editor de Neon.
-- Usa tablas propias para no interferir con tablas preexistentes.
-- No inserta datos ficticios: los partidos se cargan desde /admin.

CREATE TABLE IF NOT EXISTS copa_matches (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day text NOT NULL CHECK (day IN ('jueves', 'viernes', 'sabado')),
  date_label text NOT NULL,
  time_label text NOT NULL,
  category text NOT NULL,
  court text NOT NULL,
  team_a text NOT NULL,
  team_b text NOT NULL,
  score_a integer CHECK (score_a IS NULL OR score_a >= 0),
  score_b integer CHECK (score_b IS NULL OR score_b >= 0),
  status text NOT NULL DEFAULT 'por_jugar'
    CHECK (status IN ('por_jugar', 'en_curso', 'finalizado')),
  clock_seconds integer NOT NULL DEFAULT 0 CHECK (clock_seconds >= 0),
  clock_started_at timestamptz,
  period integer NOT NULL DEFAULT 1 CHECK (period BETWEEN 1 AND 4),
  is_running boolean NOT NULL DEFAULT false,
  featured boolean NOT NULL DEFAULT false,
  stage text NOT NULL DEFAULT 'grupo'
    CHECK (stage IN ('grupo', 'cuartos', 'semifinal', 'final')),
  penalties text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS copa_match_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id integer NOT NULL REFERENCES copa_matches(id) ON DELETE CASCADE,
  minute integer NOT NULL CHECK (minute >= 0),
  second integer NOT NULL DEFAULT 0 CHECK (second BETWEEN 0 AND 59),
  period integer NOT NULL CHECK (period BETWEEN 1 AND 4),
  team text NOT NULL CHECK (team IN ('teamA', 'teamB')),
  type text NOT NULL CHECK (type IN ('goal', 'green_card', 'yellow_card')),
  player text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS copa_match_events_match_id_created_at_idx
  ON copa_match_events (match_id, created_at DESC);
